#!/bin/sh

# Kill if restart
killall \
  redshift \
  redshift-gtk \
  nm-applet \
  blueman-applet \
  volumeicon \
  &

xset s on &
xset s 900 &
xss-lock slock +resetsaver &
xsetroot -cursor_name left_ptr &
sleep 1 && xset r rate 300 30 &
sxhkd &
$HOME/.config/polybar/launch.sh bspwm &
libinput-gestures &
nitrogen --restore &
picom --experimental-backends -c -b &
dunst &

/usr/lib/polkit-1/polkitd --no-debug &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh &

nm-applet &
blueman-applet &
redshift-gtk &
volumeicon &
xfsettingsd &
xset r rate 200 25 &
cadence --minimized &

bspc monitor -d I II III IV V VI VII VIII IX X

# Set very basic keybindings
bspc config pointer_modifier      super
bspc config pointer_action1       move
bspc config pointer_action2       resize_corner
bspc config focus_follows_pointer true

# Borders and gaps setup
bspc config border_width          1
bspc config window_gap            3
bspc config top_padding           27

# Window rules
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle	      true

# Color set
bspc config normal_border_color   "#434c5e"
bspc config active_border_color   "#4c566a"
bspc config focused_border_color  "#d8dee9"
bspc config presel_feedback_color "#8FBCBB"
bspc config urgent_border_color   "#bf616a"

# Follow
bspc rule -a Gimp         desktop='^8'  follow=on
bspc rule -a Spotify      desktop='^10' follow=on
bspc rule -a discord      desktop='^10' follow=on
bspc rule -a Thunderbird  desktop='^10' follow=on

# Floatig
bspc rule -a Pavucontrol          state=floating
bspc rule -a TelegramDesktop      state=floating
bspc rule -a zoom                 state=floating
bspc rule -a Lutris               state=floating
bspc rule -a Wine                 state=floating
bspc rule -a PacketTracer7        state=floating
bspc rule -a Gnome-screenshot     state=floating
bspc rule -a Skype                state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Pamac-manager        state=floating
bspc rule -a Processing           state=floating
bspc rule -a Lxappearance         state=floating
bspc rule -a flameshot            state=floating
bspc rule -a Blueman-manager      state=floating

# Tiled
bspc rule -a Zathura  state=tiled
bspc rule -a Emacs    state=tiled

# Weird other rules
bspc rule -a Plank layer=above manage=on border=off
