import = ["/home/cg/.config/alacritty/catppuccin/catppuccin-mocha.yml"]

[font]
size = 13.0

[font.bold]
family = "IntelOne Mono"
style = "Bold"

[font.bold_italic]
family = "IntelOne Mono"
style = "Bold Italic"

[font.italic]
family = "IntelOne Mono"
style = "Italic"

[font.normal]
family = "IntelOne Mono"
style = "Regular"
